### ISSUE TITLE
panic on interface conversion

### ISSUE THREAD

**Issue by NoSugarCoffee** [diegoholiveira/jsonlogic#51]
## reproduce
logic = `{"==":[{"var":"test"},true]}`
data = `{}`

## stack trace
```
panic: interface conversion: interface {} is bool, not string [recovered]
	panic: interface conversion: interface {} is bool, not string

goroutine 6 [running]:
testing.tRunner.func1.1(0x54d6e0, 0xc000100420)
	/home/liangliangdai/.asdf/installs/golang/1.14/go/src/testing/testing.go:941 +0x3d0
testing.tRunner.func1(0xc000132120)
	/home/liangliangdai/.asdf/installs/golang/1.14/go/src/testing/testing.go:944 +0x3f9
panic(0x54d6e0, 0xc000100420)
	/home/liangliangdai/.asdf/installs/golang/1.14/go/src/runtime/panic.go:967 +0x15d
github.com/diegoholiveira/jsonlogic.toString(0x5404a0, 0x683ee1, 0x0, 0x0)
	/home/liangliangdai/.asdf/installs/golang/1.16/go/pkg/mod/github.com/diegoholiveira/jsonlogic@v2.3.1+incompatible/helpers.go:74 +0x108
github.com/diegoholiveira/jsonlogic.equals(0x0, 0x0, 0x5404a0, 0x683ee1, 0xc00000c120)
	/home/liangliangdai/.asdf/installs/golang/1.16/go/pkg/mod/github.com/diegoholiveira/jsonlogic@v2.3.1+incompatible/comp.go:34 +0xbd
github.com/diegoholiveira/jsonlogic.operation(0xc00001c2e8, 0x2, 0x53ea80, 0xc00000c140, 0x54c500, 0xc0001003c0, 0xc000068530, 0x53a400)
	/home/liangliangdai/.asdf/installs/golang/1.16/go/pkg/mod/github.com/diegoholiveira/jsonlogic@v2.3.1+incompatible/jsonlogic.go:658 +0xa70
github.com/diegoholiveira/jsonlogic.apply(0x54c500, 0xc000100360, 0x54c500, 0xc0001003c0, 0xc000068500, 0x0)
	/home/liangliangdai/.asdf/installs/golang/1.16/go/pkg/mod/github.com/diegoholiveira/jsonlogic@v2.3.1+incompatible/jsonlogic.go:708 +0x1b5
github.com/diegoholiveira/jsonlogic.ApplyRaw(0xc000016480, 0x1d, 0x20, 0xc00001c2d8, 0x2, 0x8, 0x685ae0, 0x0, 0x1, 0xc000052748, ...)
	/home/liangliangdai/.asdf/installs/golang/1.16/go/pkg/mod/github.com/diegoholiveira/jsonlogic@v2.3.1+incompatible/jsonlogic.go:761 +0x23e
study_go2/jsonlogic.TestUsage(0xc000132120)
	/home/liangliangdai/IdeaProjects/study_go2/jsonlogic/jsonlogic_test.go:13 +0xb3
testing.tRunner(0xc000132120, 0x581c90)
	/home/liangliangdai/.asdf/installs/golang/1.14/go/src/testing/testing.go:992 +0xdc
created by testing.(*T).Run
	/home/liangliangdai/.asdf/installs/golang/1.14/go/src/testing/testing.go:1043 +0x357

Process finished with the exit code 1
```
## others
it works when modify `true` to `"true"`

![image](https://user-images.githubusercontent.com/25247325/169695450-4a7fabb9-1bb9-41ff-ae68-4fd08c6c3cd9.png)

but result different with playground, which is correct ?

![image](https://user-images.githubusercontent.com/25247325/169695493-68b814c9-26c2-42fb-b146-69d59558042b.png)

seems no judgement for bool  here 
https://github.com/diegoholiveira/jsonlogic/blob/b039a992a3a86f90d4de77ccc91c2b1b2ffcc44b/helpers.go#L64

**Comment by diegoholiveira** [comment]
Fixed in b324023c528422b52b3f02937f5d069074dc75a0
